# workflow:
#   rules:
#     - if: $CI_COMMIT_TITLE =~ /-draft$/
#       when: never
#     - if: $CI_COMMIT_BRANCH == "master"
# stages:
#   - deploy
# on-deploy:
#   stage: deploy
#   script:
#     - gem install faraday -v 1.8.0
#     - gem install dpl
#     - dpl --provider=heroku --app=$HEROKU_APP_NAME --api-key=$HEROKU_API_KEY
